services:
  user-webserver:
    image: nginx:alpine
    container_name: UserManagement-webserver
    working_dir: /application
    env_file:
      - UserManagementService/.env
    volumes:
      - ./UserManagementService/:/application
      - ./UserManagementService/sourcefiles/nginx:/etc/nginx/conf.d
    ports:
      - "${NGINX_PORT}:80"

  user-php-fpm:
    build: UserManagementService/sourcefiles/php
    container_name: UserManagement-php-fpm
    working_dir: /application
    environment:
      - PHP_WORKER_INSTALL_BCMATH=true
    volumes:
      - ./UserManagementService:/application

  user-pgsql:
    image: postgres:13
    container_name: UserManagement-pgsql
    env_file:
      - UserManagementService/.env
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${DB_PORT}:5432'

  task-webserver:
    image: nginx:alpine
    container_name: TaskManagement-webserver
    working_dir: /application
    env_file:
      - TaskManagementService/.env
    volumes:
      - ./TaskManagementService/:/application
      - ./TaskManagementService/sourcefiles/nginx:/etc/nginx/conf.d
    ports:
      - "${NGINX_PORT}:80"
  task-php-fpm:
    build: TaskManagementService/sourcefiles/php
    container_name: TaskManagement-php-fpm
    working_dir: /application
    environment:
      - PHP_WORKER_INSTALL_BCMATH=true
    volumes:
      - ./TaskManagementService:/application

  task-pgsql:
    image: postgres:13
    container_name: TaskManagement-pgsql
    env_file:
      - TaskManagementService/.env
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${DB_PORT}:5432'
  rabbitmq:
    image: rabbitmq:4.2-management
    ports:
      - '${RABBITMQ_LISTEN_PORT}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT}:15672'
    volumes:
      - './sourcefiles/rabbitmq/data:/var/lib/rabbitmq'
      - './sourcefiles/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf'